CC=g++
CXXFLAGS=-g -std=c++11 -Wall -pedantic -D_GNU_SOURCE -I.

LDFLAGS=

MAKEDEPEND=${CC} -MM
PROGRAM=test_buffer_pool

OBJS = util/buffer_pool.o test_buffer_pool.o

DEPS:= ${OBJS:%.o=%.d}

all: $(PROGRAM)

${PROGRAM}: ${OBJS}
	${CC} ${OBJS} ${LIBS} -o $@ ${LDFLAGS}

clean:
	rm -f ${PROGRAM} ${OBJS} ${DEPS}

${OBJS} ${DEPS} ${PROGRAM} : Makefile.${PROGRAM}

.PHONY : all clean

%.d : %.cpp
	${MAKEDEPEND} ${CXXFLAGS} $< -MT ${@:%.d=%.o} > $@

%.o : %.cpp
	${CC} ${CXXFLAGS} -c -o $@ $<

-include ${DEPS}
